[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD"
value = "false"
